apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskmango.fullname" . }}-frontend-config
  labels:
    {{- include "taskmango.labels" . | nindent 4 }}
data:
  API_SERVICE_URL: "http://{{ include "taskmango.fullname" . }}-api:{{ .Values.apiService.service.port }}"
  AUTH_SERVICE_URL: "http://{{ include "taskmango.fullname" . }}-auth:{{ .Values.authService.service.port }}"
