apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskmango.fullname" . }}-frontend
  labels:
    {{- include "taskmango.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontendService.replicaCount }}
  selector:
    matchLabels:
      {{- include "taskmango.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "taskmango.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontendService.image.repository }}:{{ .Values.frontendService.image.tag }}"
          imagePullPolicy: {{ .Values.frontendService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "taskmango.fullname" . }}-frontend-config
          resources:
            {{- toYaml .Values.frontendService.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
