{{- if .Values.kong.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "taskmango.fullname" . }}-ingress
  labels:
    {{- include "taskmango.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "taskmango.fullname" . }}-kong
                port:
                  number: 80
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "taskmango.fullname" . }}-kong
                port:
                  number: 80
{{- end }}