{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "taskmango.fullname" . }}
  labels:
    {{- include "taskmango.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "taskmango.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.frontendService.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "taskmango.fullname" $ }}-api
                port:
                  number: {{ $.Values.apiService.service.port }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "taskmango.fullname" $ }}-auth
                port:
                  number: {{ $.Values.authService.service.port }}
    {{- end }}
{{- end }}
