apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskmango.fullname" . }}-api-config
  labels:
    {{- include "taskmango.labels" . | nindent 4 }}
data:
  app.env: |
    DB_HOST={{ .Values.global.database.host }}
    DB_PORT={{ .Values.global.database.port | quote }}
    DB_USER={{ .Values.global.database.username }}
    DB_PASSWORD={{ .Values.global.database.password | quote }}
    DB_NAME={{ .Values.global.database.name }}
    JWT_ISSUER={{ .Values.apiService.env.JWT_ISSUER }}
    JWT_AUDIENCE={{ .Values.apiService.env.JWT_AUDIENCE }}
    JWT_SIGNING_KEY={{ .Values.apiService.env.JWT_SIGNING_KEY }}
    JWT_VALIDITY={{ .Values.apiService.env.JWT_VALIDITY }}
    API_PORT={{ .Values.apiService.service.port | quote }}
    PROBE_PORT={{ .Values.apiService.service.probePort | quote }}