apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskmango.fullname" . }}-api
  labels:
    {{- include "taskmango.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.service.type }}
  ports:
    - port: {{ .Values.apiService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.apiService.service.probePort }}
      targetPort: probe
      protocol: TCP
      name: probe
  selector:
    {{- include "taskmango.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-service