{{- if .Values.kong.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskmango.fullname" . }}-kong
  labels:
    {{- include "taskmango.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kong.replicaCount }}
  selector:
    matchLabels:
      {{- include "taskmango.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kong
  template:
    metadata:
      labels:
        {{- include "taskmango.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kong
    spec:
      containers:
        - name: kong
          image: "{{ .Values.kong.image.repository }}:{{ .Values.kong.image.tag }}"
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/opt/kong/kong.yml"
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
          ports:
            - name: proxy
              containerPort: 8000
              protocol: TCP
            - name: admin
              containerPort: 8001
              protocol: TCP
          resources:
            {{- toYaml .Values.kong.resources | nindent 12 }}
          volumeMounts:
            - name: kong-config
              mountPath: /opt/kong/kong.yml
              subPath: kong.yml
      volumes:
        - name: kong-config
          configMap:
            name: {{ include "taskmango.fullname" . }}-kong-config
{{- end }}