{{- if .Values.kong.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskmango.fullname" . }}-kong
  labels:
    {{- include "taskmango.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kong.proxy.type }}
  ports:
    - name: proxy
      port: 80
      targetPort: proxy
      protocol: TCP
      {{- if eq .Values.kong.proxy.type "NodePort" }}
      nodePort: {{ .Values.kong.proxy.http.nodePort }}
      {{- end }}
    - name: admin
      port: 8001
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "taskmango.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kong
{{- end }}