# Global values
global:
  imagePullPolicy: IfNotPresent
  database:
    name: taskmango_db
    username: "taskuser"
    password: "taskpass"
    host: taskmango-mysql
    port: 3306

# MySQL configuration
mysql:
  enabled: true
  auth:
    rootPassword: "" # if empty, one will be generated
    username: "taskuser" # dedicated user
    password: "taskpass" # Non-empty password
    database: taskmango_db
  primary:
    persistence:
      enabled: false
      size: 1Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# API Service configuration
apiService:
  enabled: true
  replicaCount: 1
  image:
    repository: randiltharusha/taskmango
    tag: apisvc-latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    probePort: 8081
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  env:
    JWT_ISSUER: "auth-service"
    JWT_AUDIENCE: "task-manager"
    JWT_SIGNING_KEY: "secret-key-change-me"
    JWT_VALIDITY: "3600"

# Auth Service configuration
authService:
  enabled: true
  replicaCount: 1
  image:
    repository: randiltharusha/taskmango
    tag: authsvc-latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9090
    probePort: 9091
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  env:
    JWT_ISSUER: "auth-service"
    JWT_AUDIENCE: "task-manager"
    JWT_SIGNING_KEY: "secret-key-change-me"
    JWT_VALIDITY: "3600"

# Kong API Gateway configuration
kong:
  enabled: true
  replicaCount: 1
  image:
    repository: kong
    tag: "3.4"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  proxy:
    type: NodePort
    http:
      nodePort: 30080
  admin:
    enabled: true
    http:
      enabled: true
      servicePort: 8001
  ingressController:
    enabled: true
    installCRDs: false
  env:
    database: "off"
    declarative_config: "/opt/kong/kong.yml"

# Database initialization job
initDb:
  enabled: true
  image:
    repository: mysql
    tag: 8.0
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
